object Versions {
    const val kotlin = "1.8.20"
    const val compose = "1.4.0"
    const val coroutines = "1.7.0"
    const val serialization = "1.4.1"
    const val ktor = "2.3.5"
    const val koin = "3.4.3"
    const val imageLoader = "1.6.3"
    const val logbackClassic = "1.2.11"
    const val kotlinWrappersBom = "1.0.0-pre.510"
    const val voyagerVersion = "1.0.0-rc08"
    const val mokoVersion = "0.23.0"
    const val okioVersion = "3.5.0"
    const val sqlDelightVersion = "1.5.5"
}